### ISSUE TITLE
Doesn't seem to be working on Atom

### ISSUE THREAD

**Issue by ggedde** [zhuzhuppx/bootstrap-vue-snippets#1]
I installed it on Atom, but not showing any snippets

**Comment by zhuzhuppx** [comment]
@ggedde you should type in b-XXX such as b-alert then tab in **vue file** or **html file**

**Comment by ggedde** [comment]
Looks like there was an update from version 0.4.0 to 0.12.0.  After that update in Atom it started working.

Thanks
